// Generated by Wrangler by running `wrangler types --env-interface CloudflareBindings`

interface CloudflareBindings {
	GROQ_API_KEY: string;
	SUPABASE_ANON_KEY: string;
	SUPABASE_URL: string;
	DB: D1Database;
}
