// Generated by Wrangler by running `wrangler types --env-interface CloudflareBindings`

interface CloudflareBindings {
	SERVER_BASE_URL: string;
	SERVER_PORT: string;
	SUPABASE_ANON_KEY: string;
	SUPABASE_URL: string;
	GROQ_API_KEY: string;
	CLOUDINARY_CLOUD_NAME: string;
	CLOUDINARY_API_KEY: string;
	CLOUDINARY_API_SECRET: string;
	DB: D1Database;
}
